### ISSUE TITLE
Implement boundary conditions 

### ISSUE THREAD

**Issue by ignasiialemany** [janniklasrose/RWcDTI#10]
Allow the user to choose boundary conditions at the end of `[Lx,Ly,Lz]`. Currently , the user can choose two types of geometries: `full` or ` block`. In both cases, the walker uses function `one_dt()` and checks if the walker is stepping out of the bounding box ` [Lx,Ly,Lz]` . Periodic boundary would mean that the walker is free to step into the following block whereas reflect would not allow walkers crossing from one box to the other. 

Implement a config parameter inside `substrate.yml` in order to be able to switch between these two options. The parameter should be called `boundary: reflect` or `boundary:periodic`.

**Comment by janniklasrose** [comment]
I would argue that if you select the `block` geometry type, you implicitly select periodic boundary conditions for that block. I would therefore say that there is no need to a new config parameter and `full` should aways reflect when a walker gets to the `LxLyLz` bounding box.

- If you want an _infinite_ domain, either specify a practically infinite domain of cells or use a transform if you can't afford to do that.
- If you want a finite domain, use a `full` geometry of appropriate `LxLyLz`.

As a side note, it might be good to verify that the bounding box `LxLyLz` fully contains the geometry, otherwise we get weird behaviour. Although that could also be left to the user.

**Comment by janniklasrose** [comment]
Uncomment and complement the below code with a suitable `if` statement based on `substrate.boundary`:
https://github.com/janniklasrose/RWcDTI/blob/2a8f96efb4d53f570b591f779af0bde143542586/%2BMonteCarlo/%40ParticleWalker/private/one_dt.m#L52-L53
